// Generated by CoffeeScript 1.6.3
var request;

request = require('request');

module.exports = {
  geocode: function(address, bingMapsKey, done) {
    var basePath, host, queryString, url;
    host = 'dev.virtualearth.net';
    basePath = 'REST/v1/Locations';
    queryString = "output=json&key=" + bingMapsKey;
    url = "http://" + host + "/" + basePath + "/" + (encodeURIComponent(address.trim())) + "?" + queryString;
    return request(url, function(err, res, body) {
      var e, json, lat, lon, resource, resourceSet, resources, _ref;
      if (err != null) {
        return done(err);
      }
      if (res.statusCode !== 200) {
        return done({
          message: "" + res.statusCode + " " + url
        });
      }
      if (_(body).isEmpty()) {
        return done({
          message: "Empty response"
        });
      }
      try {
        json = JSON.parse(body);
      } catch (_error) {
        e = _error;
        return done({
          message: "Error parsing response " + url
        });
      }
      if (!(json.resourceSets.length > 0)) {
        return done({
          message: "No resourceSets " + url
        });
      }
      if (json.resourceSets.length !== 1) {
        return done({
          message: "Multiple resourceSets " + url
        });
      }
      resourceSet = json.resourceSets[0];
      resources = resourceSet.resources;
      if (!((resources != null) && resources.length > 0)) {
        return done({
          message: "No resources " + url
        });
      }
      resource = _(resourceSet.resources).find(function(resource) {
        return resource.matchCodes.length === 1 && resource.matchCodes[0] === 'Good';
      });
      if (resource == null) {
        return done({
          message: "No resource " + url
        });
      }
      if (!((resource.point != null) && resource.point.type === 'Point')) {
        return done({
          message: "No point " + url
        });
      }
      if (!resource.point.coordinates) {
        return done({
          message: "No coordinates " + url
        });
      }
      _ref = resource.point.coordinates, lat = _ref[0], lon = _ref[1];
      return done(null, {
        lat: lat,
        lon: lon,
        resource: resource
      });
    });
  }
};
